# Generated by Django 4.1.1 on 2022-09-29 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_wikicontent_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wikisection',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='base.wikitopic'),
        ),
    ]
