# Generated by Django 4.1.1 on 2022-09-29 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_wikisection_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wikicontent',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='base.wikisection'),
        ),
        migrations.AlterField(
            model_name='wikisection',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
